[project]
name = "visualizer"
version = "0.1.0"
description = "A short description of your project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
