
name: plot-visualizer

services:
  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      janusgraph:
        condition: service_healthy
    networks:
      - jg-network

  janusgraph:
    image: janusgraph/janusgraph:latest
    platform: linux/amd64
    ports:
      - "8182:8182"
    volumes:
      - ../graph_schema/schema.groovy:/opt/janusgraph/scripts/schema.groovy
      - ../graph_schema/gremlin-server-custom.yaml:/opt/janusgraph/conf/gremlin-server.yaml
      - ../graph_schema/janusgraph-berkeleyje.properties:/opt/janusgraph/conf/janusgraph-berkeleyje.properties
      - jg-data:/opt/janusgraph/data
      - jg-index:/opt/janusgraph/index
    healthcheck:
      test: [ "CMD", "bin/gremlin.sh", "-e", "scripts/remote-connect.groovy" ]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 40s
    networks:
      - jg-network

  schema-init:
    image: janusgraph/janusgraph:latest
    platform: linux/amd64
    depends_on:
      janusgraph:
        condition: service_healthy
    volumes:
      - ../graph_schema/schema.groovy:/opt/janusgraph/scripts/schema.groovy
    entrypoint: [ "bin/gremlin.sh", "-e", "scripts/schema.groovy" ]
    environment:
      GREMLIN_REMOTE_HOSTS: janusgraph
    networks:
      - jg-network

networks:
  jg-network:
    driver: bridge

volumes:
  jg-data:
  jg-index: