gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=berkeleyje
storage.directory=/opt/janusgraph/data/unus_mundus_network
index.search.backend=lucene
index.search.directory=/opt/janusgraph/index/unus_mundus_network
graph.graphname=unus_mundus_network